quarkus:
  http:
    enable-compression: true
    cors: true
    root-path: "/api"
  resteasy:
    gzip:
      enabled: true
      max-input: 10M

countryRestClient/mp-rest/url: https://api.worldbank.org
